### ISSUE TITLE
Does the # of Jenkins Pods ever scale up?

### ISSUE THREAD

**Issue by Skilgarriff** [GoogleCloudPlatform/continuous-deployment-on-kubernetes#15]
I'm curious if the number of Jenkins pods (Masters) every is envisioned in needing to be scaled up. We currently run a Kubernetes cluster that spans multiple AZ-zones in AWS, so we would need to have a Persistent Disk that also spans multiple AZ zones.

**Comment by viglesiasce** [comment]
Sorry for the delay in getting back to you. 

The masters do not scale up today. This is a limitation in how the open source Jenkins master is implemented. CloudBees do have support for multiple masters in [their enterprise offering](https://www.cloudbees.com/products/cloudbees-jenkins-platform) but I dont have experience with it. In the future I would like to look into using the [Gearman plugin](https://wiki.jenkins-ci.org/display/JENKINS/Gearman+Plugin) in order to implement multiple masters.

**Comment by Skilgarriff** [comment]
No worries. 

Great, that actually helps a lot I think I'm going to check that plugin out and see if we can implement ourselves. Thanks!

**Comment by Skilgarriff** [comment]
Do you recommend scaling up the amount of CPU/RAM that is allotted to one of the Jenkins containers, if you don't (or still do) implement a multiple master solution.

**Comment by viglesiasce** [comment]
Yes you can keep updating your Jenkins pod template to scale up the amount of CPU and RAM.
